----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "zhTW" then
    return
end

loadstring([[
local BtWQuests = BtWQuests
local i = {
    {
        name = "Dragonflight",
        type = "expansion",
        link = "btwquests:expansion:9",
    },
    {
        name = "甦醒吧，半龍人",
        type = "chain",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        path = "Dragonflight",
    },
    {
        name = "半龍人，甦醒吧",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 64864,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:64864",
    },
    {
        name = "整裝出發",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 64865,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:64865",
    },
    {
        name = "秘法守護者",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 64863,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:64863",
    },
    {
        name = "進入大熔爐",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 64866,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:64866",
    },
    {
        name = "門口的龍",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 64871,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:64871",
    },
    {
        name = "秘法入侵",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65615,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65615",
    },
    {
        name = "體內的烈火",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 64872,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:64872",
    },
    {
        name = "舒展你的翅膀",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 64873,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:64873",
    },
    {
        name = "訓練視同作戰",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65036,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65036",
    },
    {
        name = "治癒者火山口",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65060,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65060",
    },
    {
        name = "進入巢穴",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65063,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65063",
    },
    {
        name = "托諾",
        type = "npc",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "npc",
            id = 184166,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
    },
    {
        name = "劇毒的問題",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65073,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65073",
    },
    {
        name = "簡單的獵物",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65074,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65074",
    },
    {
        name = "救命！",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65071,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65071",
    },
    {
        name = "人道優先",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65307,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65307",
    },
    {
        name = "永遠銘記",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 66324,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:66324",
    },
    {
        name = "治療之翼",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65075,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65075",
    },
    {
        name = "風裂火山口",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65045,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65045",
    },
    {
        name = "騎士精神不死",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 72263,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:72263",
    },
    {
        name = "與塔拉賽克一戰",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65049,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65049",
    },
    {
        name = "召喚而來的軍隊",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65050,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65050",
    },
    {
        name = "洪荒使者",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65046,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65046",
    },
    {
        name = "黯鱗龍隊",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65052,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65052",
    },
    {
        name = "向安珀莎報到",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65057,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65057",
    },
    {
        name = "護存或破滅",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65701,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65701",
    },
    {
        name = "霜石密庫",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65084,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65084",
    },
    {
        name = "內有大獎",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65087,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65087",
    },
    {
        name = "快跑！",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65097,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65097",
    },
    {
        name = "勇敢的後果",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65098,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65098",
    },
    {
        name = "最後的命令",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65100,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65100",
    },
    {
        name = "龍人的人緣",
        type = "quest",
        restrictions = {
            {
                type = "class",
                id = 13,
            },
            {
                type = "faction",
                id = BtWQuests.Constant.Faction.Alliance,
            },
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65286,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65286",
    },
    {
        name = "精神上的盟友",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 66237,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:66237",
    },
    {
        name = "展翅高飛",
        type = "quest",
        restrictions = {
            {
                type = "class",
                id = 13,
            },
            {
                type = "faction",
                id = BtWQuests.Constant.Faction.Alliance,
            },
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 66513,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:66513",
    },
    {
        name = "展翅高飛",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 66534,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:66534",
    },
    {
        name = "守護巨龍的邀約",
        type = "quest",
        restrictions = {
            {
                type = "class",
                id = 13,
            },
            {
                type = "faction",
                id = BtWQuests.Constant.Faction.Alliance,
            },
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 66577,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:66577",
    },
    {
        name = "守護巨龍的邀約",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65437,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65437",
    },
    {
        name = "經典的龍人造型",
        type = "quest",
        restrictions = {
            {
                type = "class",
                id = 13,
            },
            {
                type = "faction",
                id = BtWQuests.Constant.Faction.Alliance,
            },
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65101,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65101",
    },
    {
        name = "經典的龍人造型",
        type = "quest",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100001",
        scrollTo = {
            type = "quest",
            id = 65613,
        },
        path = "Dragonflight > 甦醒吧，半龍人",
        tooltip = "quest:65613",
    },
    {
        name = "龍鱗遠征隊",
        type = "chain",
        link = "btwquests:chain:100091",
        path = "Dragonflight",
    },
    {
        name = "巨龍群島等著你",
        type = "quest",
        restrictions = {
            type = "class",
            ids = {
                1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 
            },
        },
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 65435,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:65435",
    },
    {
        name = "守護巨龍的邀約",
        type = "quest",
        restrictions = {
            type = "class",
            ids = {
                1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 
            },
        },
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 65437,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:65437",
    },
    {
        name = "Scalecommander Azurathel",
        type = "npc",
        restrictions = {
            {
                type = "class",
                id = 13,
            },
            {
                type = "faction",
                id = BtWQuests.Constant.Faction.Alliance,
            },
        },
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "npc",
            id = 189603,
        },
        path = "Dragonflight > 龍鱗遠征隊",
    },
    {
        name = "龍隊指揮官辛德瑞翠絲",
        type = "npc",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "npc",
            id = 184786,
        },
        path = "Dragonflight > 龍鱗遠征隊",
    },
    {
        name = "Toddy Whiskers",
        type = "npc",
        restrictions = {
            {
                type = "class",
                id = 13,
            },
            {
                type = "faction",
                id = BtWQuests.Constant.Faction.Alliance,
            },
        },
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "npc",
            id = 189602,
        },
        path = "Dragonflight > 龍鱗遠征隊",
    },
    {
        name = "娜蕾迪亞‧河光",
        type = "npc",
        restrictions = {
            type = "class",
            id = 13,
        },
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "npc",
            id = 184793,
        },
        path = "Dragonflight > 龍鱗遠征隊",
    },
    {
        name = "黑曜衛隊",
        type = "quest",
        restrictions = 924,
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 72240,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:72240",
    },
    {
        name = "黑爪兵團",
        type = "quest",
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 72256,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:72256",
    },
    {
        name = "遠征行動",
        type = "quest",
        restrictions = 924,
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 66589,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:66589",
    },
    {
        name = "遠征行動",
        type = "quest",
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 65443,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:65443",
    },
    {
        name = "風中的低語",
        type = "quest",
        restrictions = 924,
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 66596,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:66596",
    },
    {
        name = "風中的低語",
        type = "quest",
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 65439,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:65439",
    },
    {
        name = "洪荒威脅",
        type = "quest",
        restrictions = 924,
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 70048,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:70048",
    },
    {
        name = "洪荒威脅",
        type = "quest",
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 69923,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:69923",
    },
    {
        name = "追逐風暴",
        type = "quest",
        restrictions = 924,
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 70050,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:70050",
    },
    {
        name = "追逐風暴",
        type = "quest",
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 69944,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:69944",
    },
    {
        name = "提爾的遺產：過往的秘密",
        type = "quest",
        restrictions = 924,
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 66458,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:66458",
    },
    {
        name = "提爾的遺產：過往的秘密",
        type = "quest",
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 66586,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:66586",
    },
    {
        name = "追逐風暴",
        type = "quest",
        restrictions = 924,
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 70050,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:70050",
    },
    {
        name = "平定風暴",
        type = "quest",
        link = "btwquests:chain:100091",
        scrollTo = {
            type = "quest",
            id = 69925,
        },
        path = "Dragonflight > 龍鱗遠征隊",
        tooltip = "quest:69925",
    },
}

BtWQuestsDatabase:AddSearchBuckets({
    ["大"] = { i[6], i[30], },
    ["巢"] = { i[13], },
    ["！"] = { i[17], i[31], },
    ["征"] = { i[42], i[51], i[52], },
    ["t g"] = { i[1], },
    ["揮"] = { i[46], },
    ["命"] = { i[17], i[33], },
    ["a c"] = { i[45], },
    ["約"] = { i[38], i[39], i[44], },
    ["d c"] = { i[45], },
    ["e c"] = { i[45], },
    ["獵"] = { i[16], },
    ["c c"] = { i[45], },
    ["辛"] = { i[46], },
    ["道"] = { i[18], },
    ["n c"] = { i[45], },
    ["o c"] = { i[45], },
    ["t c"] = { i[45], },
    ["u c"] = { i[45], },
    ["r c"] = { i[45], },
    ["s c"] = { i[45], },
    ["h c"] = { i[45], },
    ["l c"] = { i[45], },
    ["m c"] = { i[45], },
    ["‧"] = { i[48], },
    ["瑞"] = { i[46], },
    ["果"] = { i[32], },
    ["omm"] = { i[45], },
    ["衛"] = { i[49], },
    ["緣"] = { i[34], },
    ["內"] = { i[9], i[30], },
    ["n a"] = { i[1], i[45], },
    ["o a"] = { i[1], i[45], },
    ["g d"] = { i[1], },
    ["f d"] = { i[1], },
    ["m d"] = { i[45], },
    ["l d"] = { i[1], i[45], },
    ["t a"] = { i[1], i[45], },
    ["u a"] = { i[45], },
    ["f a"] = { i[1], },
    ["g a"] = { i[1], },
    ["h a"] = { i[1], i[45], },
    ["i a"] = { i[1], },
    ["e d"] = { i[45], i[47], },
    ["d d"] = { i[1], i[45], i[47], },
    ["c d"] = { i[45], },
    ["m a"] = { i[45], },
    ["y d"] = { i[47], },
    ["w d"] = { i[47], },
    ["nde"] = { i[45], },
    ["z d"] = { i[45], },
    ["o d"] = { i[1], i[45], i[47], },
    ["n d"] = { i[1], i[45], },
    ["u d"] = { i[45], },
    ["t d"] = { i[1], i[45], i[47], },
    ["s d"] = { i[45], i[47], },
    ["r d"] = { i[1], i[45], i[47], },
    ["gon"] = { i[1], },
    ["體"] = { i[9], },
    ["com"] = { i[45], },
    ["nfl"] = { i[1], },
    ["賽"] = { i[23], },
    ["a a"] = { i[1], i[45], },
    ["c a"] = { i[45], },
    ["d a"] = { i[1], i[45], },
    ["e a"] = { i[45], },
    ["l h"] = { i[1], i[45], },
    ["d g"] = { i[1], },
    ["g g"] = { i[1], },
    ["o h"] = { i[1], i[45], i[47], },
    ["醒"] = { i[2], i[3], },
    ["守"] = { i[5], i[38], i[39], i[44], },
    ["r h"] = { i[1], i[45], i[47], },
    ["s h"] = { i[45], i[47], },
    ["t h"] = { i[1], i[45], i[47], },
    ["u h"] = { i[45], },
    ["o g"] = { i[1], },
    ["n g"] = { i[1], },
    ["y h"] = { i[47], },
    ["z h"] = { i[45], },
    ["r g"] = { i[1], },
    ["優"] = { i[18], },
    ["訓"] = { i[11], },
    ["蕾"] = { i[48], },
    ["a h"] = { i[1], i[45], },
    ["c h"] = { i[45], },
    ["d h"] = { i[1], i[45], i[47], },
    ["e h"] = { i[45], i[47], },
    ["f h"] = { i[1], },
    ["珀"] = { i[27], },
    ["a g"] = { i[1], },
    ["i h"] = { i[1], i[47], },
    ["ght"] = { i[1], },
    ["士"] = { i[22], },
    ["穴"] = { i[13], },
    ["whi"] = { i[47], },
    ["精"] = { i[22], i[35], },
    ["w e"] = { i[47], },
    ["群"] = { i[43], },
    ["u e"] = { i[45], },
    ["t e"] = { i[45], i[47], },
    ["z e"] = { i[45], },
    ["s i"] = { i[47], },
    ["t i"] = { i[1], i[47], },
    ["n f"] = { i[1], },
    ["o f"] = { i[1], },
    ["g i"] = { i[1], },
    ["d e"] = { i[45], i[47], },
    ["r f"] = { i[1], },
    ["the"] = { i[45], },
    ["i e"] = { i[47], },
    ["d i"] = { i[1], i[47], },
    ["o e"] = { i[45], i[47], },
    ["n e"] = { i[45], },
    ["o i"] = { i[1], i[47], },
    ["l e"] = { i[45], },
    ["s e"] = { i[45], i[47], },
    ["n i"] = { i[1], },
    ["k i"] = { i[47], },
    ["l i"] = { i[1], },
    ["你"] = { i[10], i[43], },
    ["敢"] = { i[32], },
    ["a i"] = { i[1], },
    ["存"] = { i[28], },
    ["c e"] = { i[45], },
    ["a e"] = { i[45], },
    ["練"] = { i[11], },
    ["人"] = { i[2], i[3], i[18], i[34], i[40], i[41], },
    ["盟"] = { i[35], },
    ["最"] = { i[33], },
    ["上"] = { i[35], },
    ["o s"] = { i[45], i[47], },
    ["h k"] = { i[47], },
    ["m s"] = { i[45], },
    ["n s"] = { i[45], },
    ["k s"] = { i[47], },
    ["l s"] = { i[45], },
    ["i s"] = { i[47], },
    ["產"] = { i[59], i[60], },
    ["o k"] = { i[47], },
    ["h s"] = { i[45], i[47], },
    ["e s"] = { i[45], i[47], },
    ["r k"] = { i[47], },
    ["c s"] = { i[45], },
    ["d s"] = { i[45], i[47], },
    ["a s"] = { i[45], },
    ["u r"] = { i[45], },
    ["w r"] = { i[47], },
    ["r r"] = { i[1], i[45], i[47], },
    ["t r"] = { i[1], i[45], i[47], },
    ["s r"] = { i[45], i[47], },
    ["n r"] = { i[1], i[45], },
    ["m r"] = { i[45], },
    ["o r"] = { i[1], i[45], i[47], },
    ["i r"] = { i[1], i[47], },
    ["l r"] = { i[1], i[45], },
    ["k r"] = { i[47], },
    ["後"] = { i[32], i[33], },
    ["a f"] = { i[1], },
    ["f f"] = { i[1], },
    ["物"] = { i[16], },
    ["d f"] = { i[1], },
    ["入"] = { i[6], i[8], i[13], },
    ["h f"] = { i[1], },
    ["i f"] = { i[1], },
    ["高"] = { i[36], i[37], },
    ["不"] = { i[22], },
    ["o l"] = { i[1], i[45], },
    ["r l"] = { i[1], i[45], },
    ["u t"] = { i[45], },
    ["t t"] = { i[1], i[45], i[47], },
    ["s t"] = { i[45], i[47], },
    ["r t"] = { i[1], i[45], i[47], },
    ["m l"] = { i[45], },
    ["o t"] = { i[1], i[45], i[47], },
    ["n t"] = { i[1], i[45], },
    ["m t"] = { i[45], },
    ["l t"] = { i[1], i[45], },
    ["一"] = { i[23], },
    ["i t"] = { i[1], i[47], },
    ["h t"] = { i[1], i[45], i[47], },
    ["g t"] = { i[1], },
    ["f t"] = { i[1], },
    ["a l"] = { i[1], i[45], },
    ["d t"] = { i[1], i[45], i[47], },
    ["c t"] = { i[45], },
    ["a t"] = { i[1], i[45], },
    ["h l"] = { i[1], i[45], },
    ["g l"] = { i[1], },
    ["i l"] = { i[1], },
    ["報"] = { i[27], },
    ["c l"] = { i[45], },
    ["f l"] = { i[1], },
    ["記"] = { i[19], },
    ["令"] = { i[33], },
    ["e r"] = { i[45], i[47], },
    ["h r"] = { i[1], i[45], i[47], },
    ["g r"] = { i[1], },
    ["der"] = { i[45], },
    ["a r"] = { i[1], i[45], },
    ["d r"] = { i[1], i[45], i[47], },
    ["c r"] = { i[45], },
    ["ker"] = { i[47], },
    ["視"] = { i[11], },
    ["w k"] = { i[47], },
    ["igh"] = { i[1], },
    ["的"] = { i[7], i[9], i[10], i[15], i[16], i[24], i[32], i[33], i[34], i[35], i[38], i[39], i[40], i[41], i[44], i[53], i[54], i[59], i[60], },
    ["t k"] = { i[47], },
    ["y s"] = { i[47], },
    ["z s"] = { i[45], },
    ["w s"] = { i[47], },
    ["拉"] = { i[23], },
    ["u s"] = { i[45], },
    ["s s"] = { i[45], i[47], },
    ["t s"] = { i[45], i[47], },
    ["z t"] = { i[45], },
    ["發"] = { i[4], },
    ["河"] = { i[48], },
    ["lig"] = { i[1], },
    ["娜"] = { i[48], },
    ["托"] = { i[14], },
    ["rat"] = { i[45], },
    ["，"] = { i[2], i[3], },
    ["翅"] = { i[10], i[36], i[37], },
    ["題"] = { i[15], },
    ["療"] = { i[20], },
    ["膀"] = { i[10], },
    ["行"] = { i[51], i[52], },
    ["而"] = { i[24], },
    ["出"] = { i[4], },
    ["半"] = { i[2], i[3], },
    ["秘"] = { i[5], i[8], i[59], i[60], },
    ["脅"] = { i[55], i[56], },
    ["甦"] = { i[2], i[3], },
    ["火"] = { i[9], i[12], i[21], },
    ["友"] = { i[35], },
    ["h y"] = { i[47], },
    ["i y"] = { i[47], },
    ["喚"] = { i[24], },
    ["e z"] = { i[45], },
    ["d z"] = { i[45], },
    ["c z"] = { i[45], },
    ["k y"] = { i[47], },
    ["先"] = { i[18], },
    ["d y"] = { i[47], },
    ["e y"] = { i[47], },
    ["y y"] = { i[47], },
    ["w y"] = { i[47], },
    ["石"] = { i[29], },
    ["o y"] = { i[47], },
    ["t y"] = { i[47], },
    ["r y"] = { i[47], },
    ["s y"] = { i[47], },
    ["ht "] = { i[1], },
    ["z o"] = { i[45], },
    ["u o"] = { i[45], },
    ["t o"] = { i[1], i[45], i[47], },
    ["s o"] = { i[45], i[47], },
    ["鱗"] = { i[26], i[42], },
    ["y o"] = { i[47], },
    ["w o"] = { i[47], },
    ["dra"] = { i[1], },
    ["典"] = { i[40], i[41], },
    ["侵"] = { i[8], },
    ["烈"] = { i[9], },
    ["邀"] = { i[38], i[39], i[44], },
    ["azu"] = { i[45], },
    ["救"] = { i[17], },
    ["z m"] = { i[45], },
    ["z n"] = { i[45], },
    ["r m"] = { i[45], },
    ["u m"] = { i[45], },
    ["t m"] = { i[45], },
    ["吧"] = { i[2], i[3], },
    ["s n"] = { i[45], },
    ["m m"] = { i[45], },
    ["u n"] = { i[45], },
    ["o m"] = { i[45], },
    ["n m"] = { i[45], },
    ["c m"] = { i[45], },
    ["l n"] = { i[1], i[45], },
    ["d m"] = { i[45], },
    ["n n"] = { i[1], i[45], },
    ["o n"] = { i[1], i[45], },
    ["h m"] = { i[45], },
    ["簡"] = { i[16], },
    ["a m"] = { i[45], },
    ["洪"] = { i[25], i[55], i[56], },
    ["裝"] = { i[4], },
    ["："] = { i[59], i[60], },
    ["來"] = { i[24], },
    ["造"] = { i[40], i[41], },
    ["ura"] = { i[45], },
    ["逐"] = { i[57], i[58], i[61], },
    ["單"] = { i[16], },
    ["l o"] = { i[1], i[45], },
    ["k o"] = { i[47], },
    ["曜"] = { i[49], },
    ["展"] = { i[10], i[36], i[37], },
    ["o o"] = { i[1], i[45], i[47], },
    ["n o"] = { i[1], i[45], },
    ["e o"] = { i[45], i[47], },
    ["d o"] = { i[1], i[45], i[47], },
    ["c o"] = { i[45], },
    ["問"] = { i[15], },
    ["h o"] = { i[1], i[45], i[47], },
    ["g o"] = { i[1], },
    ["f o"] = { i[1], },
    ["克"] = { i[23], },
    ["跑"] = { i[31], },
    ["a o"] = { i[1], i[45], },
    ["遠"] = { i[19], i[42], i[51], i[52], },
    ["霜"] = { i[29], },
    ["c n"] = { i[45], },
    ["著"] = { i[43], },
    ["e n"] = { i[45], },
    ["f n"] = { i[1], },
    ["g n"] = { i[1], },
    ["h n"] = { i[1], i[45], },
    ["i n"] = { i[1], },
    ["man"] = { i[45], },
    ["翠"] = { i[46], },
    ["d w"] = { i[47], },
    ["a n"] = { i[1], i[45], },
    ["y w"] = { i[47], },
    ["暴"] = { i[57], i[58], i[61], i[62], },
    ["er "] = { i[45], },
    ["與"] = { i[23], },
    ["神"] = { i[22], i[35], },
    ["w w"] = { i[47], },
    ["r w"] = { i[47], },
    ["t w"] = { i[47], },
    ["s w"] = { i[47], },
    ["o w"] = { i[47], },
    ["fli"] = { i[1], },
    ["l u"] = { i[45], },
    ["爾"] = { i[59], i[60], },
    ["h u"] = { i[45], },
    ["兵"] = { i[50], },
    ["e u"] = { i[45], },
    ["d u"] = { i[45], },
    ["c u"] = { i[45], },
    ["a u"] = { i[45], },
    ["毒"] = { i[15], },
    ["z u"] = { i[45], },
    ["u u"] = { i[45], },
    ["t u"] = { i[45], },
    ["s u"] = { i[45], },
    ["r u"] = { i[45], },
    ["ers"] = { i[47], },
    ["o u"] = { i[45], },
    ["n u"] = { i[45], },
    ["劇"] = { i[15], },
    ["熔"] = { i[6], },
    ["遺"] = { i[59], i[60], },
    ["el "] = { i[45], },
    ["eco"] = { i[45], },
    ["lec"] = { i[45], },
    ["定"] = { i[62], },
    ["平"] = { i[62], },
    ["往"] = { i[59], i[60], },
    ["過"] = { i[59], i[60], },
    ["提"] = { i[59], i[60], },
    ["追"] = { i[57], i[58], i[61], },
    ["威"] = { i[55], i[56], },
    ["t n"] = { i[1], i[45], },
    ["黑"] = { i[49], i[50], },
    ["口"] = { i[7], i[12], i[21], },
    ["中"] = { i[53], i[54], },
    ["動"] = { i[51], i[52], },
    ["低"] = { i[53], i[54], },
    ["騎"] = { i[22], },
    ["爪"] = { i[50], },
    ["法"] = { i[5], i[8], },
    ["裂"] = { i[21], },
    ["團"] = { i[50], },
    ["光"] = { i[48], },
    ["k w"] = { i[47], },
    ["亞"] = { i[48], },
    ["勇"] = { i[32], },
    ["s a"] = { i[45], },
    ["a z"] = { i[45], },
    ["莎"] = { i[27], },
    ["翼"] = { i[20], },
    ["指"] = { i[46], },
    ["護"] = { i[5], i[28], i[38], i[39], i[44], },
    ["y k"] = { i[47], },
    ["作"] = { i[11], },
    ["y e"] = { i[47], },
    ["龍"] = { i[2], i[3], i[7], i[26], i[34], i[38], i[39], i[40], i[41], i[42], i[43], i[44], i[46], },
    ["黯"] = { i[26], },
    ["h e"] = { i[45], i[47], },
    ["y i"] = { i[47], },
    ["w h"] = { i[47], },
    ["y r"] = { i[47], },
    ["y t"] = { i[47], },
    ["荒"] = { i[25], i[55], i[56], },
    ["t f"] = { i[1], },
    ["e w"] = { i[47], },
    ["e i"] = { i[47], },
    ["e k"] = { i[47], },
    ["h w"] = { i[47], },
    ["m e"] = { i[45], },
    ["r o"] = { i[1], i[45], i[47], },
    ["w i"] = { i[47], },
    ["風"] = { i[21], i[53], i[54], i[57], i[58], i[61], i[62], },
    ["r e"] = { i[45], i[47], },
    ["and"] = { i[45], },
    ["w t"] = { i[47], },
    ["迪"] = { i[48], },
    ["d k"] = { i[47], },
    ["i w"] = { i[47], },
    ["i k"] = { i[47], },
    ["sca"] = { i[45], },
    ["向"] = { i[27], },
    ["k e"] = { i[47], },
    ["ath"] = { i[45], },
    ["k h"] = { i[47], },
    ["k d"] = { i[47], },
    ["諾"] = { i[14], },
    ["u z"] = { i[45], },
    ["k k"] = { i[47], },
    ["k t"] = { i[47], },
    ["u l"] = { i[45], },
    ["獎"] = { i[30], },
    ["t z"] = { i[45], },
    ["z l"] = { i[45], },
    ["s k"] = { i[47], },
    ["rs "] = { i[47], },
    ["安"] = { i[27], },
    ["ske"] = { i[47], },
    ["isk"] = { i[47], },
    ["his"] = { i[47], },
    ["tod"] = { i[47], },
    ["i d"] = { i[1], i[47], },
    ["h d"] = { i[1], i[45], i[47], },
    ["舒"] = { i[10], },
    ["r a"] = { i[1], i[45], },
    ["或"] = { i[28], },
    ["a d"] = { i[1], i[45], },
    ["l a"] = { i[1], i[45], },
    ["r n"] = { i[1], i[45], },
    ["zur"] = { i[45], },
    ["語"] = { i[53], i[54], },
    ["l m"] = { i[45], },
    ["使"] = { i[25], },
    ["e m"] = { i[45], },
    ["dy "] = { i[47], },
    ["ddy"] = { i[47], },
    ["永"] = { i[19], },
    ["odd"] = { i[47], },
    ["絲"] = { i[46], },
    ["e t"] = { i[45], i[47], },
    ["飛"] = { i[36], i[37], },
    ["hel"] = { i[45], },
    ["德"] = { i[46], },
    ["官"] = { i[46], },
    ["破"] = { i[28], },
    ["快"] = { i[31], },
    ["爐"] = { i[6], },
    ["ale"] = { i[45], },
    ["s z"] = { i[45], },
    ["s l"] = { i[45], },
    ["ago"] = { i[1], },
    ["s m"] = { i[45], },
    ["n h"] = { i[1], i[45], },
    ["f g"] = { i[1], },
    ["i g"] = { i[1], },
    ["h g"] = { i[1], },
    ["l g"] = { i[1], },
    ["i o"] = { i[1], i[47], },
    ["onf"] = { i[1], },
    ["m o"] = { i[45], },
    ["g h"] = { i[1], },
    ["h h"] = { i[1], i[45], i[47], },
    ["e e"] = { i[45], i[47], },
    ["之"] = { i[20], },
    ["d n"] = { i[1], i[45], },
    ["e l"] = { i[45], },
    ["者"] = { i[5], i[12], i[25], },
    ["癒"] = { i[12], },
    ["經"] = { i[40], i[41], },
    ["進"] = { i[6], i[13], },
    ["治"] = { i[12], i[20], },
    ["z r"] = { i[45], },
    ["山"] = { i[12], i[21], },
    ["z a"] = { i[45], },
    ["z c"] = { i[45], },
    ["密"] = { i[29], i[59], i[60], },
    ["i i"] = { i[1], i[47], },
    ["l f"] = { i[1], },
    ["庫"] = { i[29], },
    ["h i"] = { i[1], i[47], },
    ["整"] = { i[4], },
    ["f i"] = { i[1], },
    ["r i"] = { i[1], i[47], },
    ["cal"] = { i[45], },
    ["死"] = { i[22], },
    ["隊"] = { i[24], i[26], i[42], i[46], i[49], },
    ["銘"] = { i[19], },
    ["m u"] = { i[45], },
    ["等"] = { i[43], },
    ["o z"] = { i[45], },
    ["n z"] = { i[45], },
    ["塔"] = { i[23], },
    ["同"] = { i[11], },
    ["有"] = { i[30], },
    ["r z"] = { i[45], },
    ["戰"] = { i[11], i[23], },
    ["h z"] = { i[45], },
    ["m h"] = { i[45], },
    ["到"] = { i[27], },
    ["m z"] = { i[45], },
    ["l z"] = { i[45], },
    ["m n"] = { i[45], },
    ["mma"] = { i[45], },
    ["召"] = { i[24], },
    ["r s"] = { i[45], i[47], },
    ["巨"] = { i[38], i[39], i[43], i[44], },
    ["g f"] = { i[1], },
    ["l l"] = { i[1], i[45], },
    ["n l"] = { i[1], i[45], },
    ["t l"] = { i[1], i[45], },
    ["島"] = { i[43], },
    ["型"] = { i[40], i[41], },
    ["d l"] = { i[1], i[45], },
    ["f r"] = { i[1], },
    ["滅"] = { i[28], },
    ["rag"] = { i[1], },
    ["門"] = { i[7], },
    ["軍"] = { i[24], },
    ["z z"] = { i[45], },
})
]])()
